// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfpj3aDgu37eyfQJiufE1YBim8HFb9QY',
    appId: '1:1022710248695:web:7379d145ef6a3214cb4ff2',
    messagingSenderId: '1022710248695',
    projectId: 'flutterchatapp-2f36b',
    authDomain: 'flutterchatapp-2f36b.firebaseapp.com',
    storageBucket: 'flutterchatapp-2f36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbJLx9roIRuujt8WVw6OH1KR5XQffWgps',
    appId: '1:1022710248695:android:1f127e06b5377debcb4ff2',
    messagingSenderId: '1022710248695',
    projectId: 'flutterchatapp-2f36b',
    storageBucket: 'flutterchatapp-2f36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOGuDPwEdRw9Vyy75Wk2gtBjBlhZle_Q',
    appId: '1:1022710248695:ios:486d16c762f692a7cb4ff2',
    messagingSenderId: '1022710248695',
    projectId: 'flutterchatapp-2f36b',
    storageBucket: 'flutterchatapp-2f36b.appspot.com',
    iosClientId: '1022710248695-ljab8g375egnr630iku72v515t142ip8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOGuDPwEdRw9Vyy75Wk2gtBjBlhZle_Q',
    appId: '1:1022710248695:ios:486d16c762f692a7cb4ff2',
    messagingSenderId: '1022710248695',
    projectId: 'flutterchatapp-2f36b',
    storageBucket: 'flutterchatapp-2f36b.appspot.com',
    iosClientId: '1022710248695-ljab8g375egnr630iku72v515t142ip8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
